In [194]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay, roc_auc_score, roc_curve, precision_recall_curve, auc, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, RandomizedSearchCV, StratifiedKFold
from sklearn.preprocessing import StandardScaler, PowerTransformer, PolynomialFeatures, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from skopt.space import Real, Integer, Categorical
from scipy.stats import randint, uniform
from skopt import BayesSearchCV
from sklearn.pipeline import Pipeline
from category_encoders import BinaryEncoder, TargetEncoder, WOEEncoder

import optuna

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, ElasticNet

In [195]:
train = ('/kaggle/input/recruitment-task-for-gdsc-ml/MiNDAT.csv', '/root/.cache/kagglehub/competitions/recruitment-task-for-gdsc-ml/MiNDAT.csv', 'Data/mindat.csv')
test = ('/kaggle/input/recruitment-task-for-gdsc-ml/MiNDAT_UNK.csv', '/root/.cache/kagglehub/competitions/recruitment-task-for-gdsc-ml/MiNDAT_UNK.csv', 'data/mindat_unk.csv')

In [196]:
df = pd.read_csv(train[2], index_col='LOCAL_IDENTIFIER')
df_test = pd.read_csv(test[2], index_col='LOCAL_IDENTIFIER')

In [197]:
df

,Z~x0<k,"vzo.""",+U@,A>.,hp!,>?64:,@wnsk>R,"U""r",&%)LTaWRb,r1Ng,...,v0rt3X,^%a;,b1oRb13,v1rt3X,0HU2N='U,ZrK,.6AvGp,3I\y,b2oRb13,CORRUCYSTIC_DENSITY
LOCAL_IDENTIFIER,,,,,,,,,,,,,,,,,,,,,
0,0.896836,-0.916578,0.632930,0.632930,-0.186669,0.422301,-0.908760,0.355945,-0.116258,0.388952,...,0.874539,-0.146314,-8.658635,0.672180,0.940507,0.117237,0.655947,-0.643482,-7.553254,521.443834
1,0.785652,-0.031439,0.265600,0.265600,NaN,0.636177,0.324519,0.933113,-0.975176,-0.529054,...,NaN,0.817420,5.426208,1.009423,-0.926698,0.974193,1.099751,0.026357,1.097666,373.696925
2,0.294313,-0.135393,0.950750,0.950750,-0.447654,0.953560,-0.178530,0.239216,0.390651,0.319620,...,1.888184,0.115265,4.255919,0.029037,NaN,3.446213,-1.007350,0.806074,1.858609,398.622235
3,0.497446,-0.049535,0.141023,0.141023,1.194801,0.000026,-1.032371,0.818995,NaN,0.031635,...,0.100983,0.907092,4.645116,-0.255313,1.797700,1.005194,1.278741,-0.818691,2.812549,527.945234
4,0.605701,1.453710,0.126049,0.126049,-0.635441,0.600073,0.776764,0.907868,-0.180334,0.662187,...,-0.894951,NaN,-1.337387,0.393958,-0.373289,0.427955,-0.726291,1.274686,10.512384,575.052682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,NaN,-0.837980,0.857335,0.857335,-0.900921,0.305825,-1.759959,0.379284,-0.431987,-0.534191,...,0.481267,NaN,6.246344,1.023857,-0.428366,NaN,0.667137,-0.308231,2.791238,235.995368
11996,0.881287,1.647118,NaN,0.239317,-1.544021,0.205085,-0.387830,0.252647,0.550154,0.167350,...,1.700230,-1.311655,-8.038122,0.146051,1.340027,-0.228400,-0.535165,-0.142828,-7.382469,421.925749
11997,0.061169,-0.483820,0.879857,NaN,-0.161385,0.914789,-1.050923,0.051287,0.019750,0.173550,...,1.761554,-1.122804,3.745146,-0.132992,-0.812099,-1.522920,-0.115161,0.182573,2.058194,206.700030
11998,0.715243,-1.030500,0.014586,0.014586,0.165240,0.285510,1.637212,0.933848,0.169283,0.708749,...,0.929562,-0.172041,3.586954,0.457671,-1.395188,1.438169,-0.339109,0.069263,3.009714,605.979254
11999,0.284834,0.506821,0.088109,0.088109,-2.330336,0.619314,NaN,0.585977,-0.645238,0.198801,...,-0.906718,-1.108863,-1.158125,0.644874,1.842947,-1.276094,0.489357,0.290644,9.900477,674.972934

In [198]:
df.isnull().sum()

Z~x0<k                 1009
vzo."                   964
+U@                     971
A>.                     945
hp!                     990
>?64:                   929
@wnsk>R                 919
U"r                    1004
&%)LTaWRb               963
r1Ng                    969
|G}                     962
TSWm                    981
r2Ng                   1000
maT_r                   962
@V9                     938
T\!                     954
14W$Q                  1007
ZZw3=!t                 987
.o<m                    965
.b6nl                   907
<!!                     986
F'3Ku                   954
~7*                     963
MINDSPIKE_VERSION      1951
9Z/5)2                  950
%IiL7w                  939
!;@Jw                   997
fPqsI                   974
ZVf                     939
i]7V                    936
Jv[i                    961
;<"<i(T                 890
Kj,                     973
w-u:jN'qI               914
PZ8                     978
jNhEum                  960
]xq                     940
v0rt3X                  936
^%a;                    964
b1oRb13                 986
v1rt3X                  937
0HU2N='U                957
ZrK                     963
.6AvGp                  921
3I\y                    873
b2oRb13                 934
CORRUCYSTIC_DENSITY     974
dtype: int64

In [199]:
df = df.dropna(subset=['CORRUCYSTIC_DENSITY']).copy()
df

,Z~x0<k,"vzo.""",+U@,A>.,hp!,>?64:,@wnsk>R,"U""r",&%)LTaWRb,r1Ng,...,v0rt3X,^%a;,b1oRb13,v1rt3X,0HU2N='U,ZrK,.6AvGp,3I\y,b2oRb13,CORRUCYSTIC_DENSITY
LOCAL_IDENTIFIER,,,,,,,,,,,,,,,,,,,,,
0,0.896836,-0.916578,0.632930,0.632930,-0.186669,0.422301,-0.908760,0.355945,-0.116258,0.388952,...,0.874539,-0.146314,-8.658635,0.672180,0.940507,0.117237,0.655947,-0.643482,-7.553254,521.443834
1,0.785652,-0.031439,0.265600,0.265600,NaN,0.636177,0.324519,0.933113,-0.975176,-0.529054,...,NaN,0.817420,5.426208,1.009423,-0.926698,0.974193,1.099751,0.026357,1.097666,373.696925
2,0.294313,-0.135393,0.950750,0.950750,-0.447654,0.953560,-0.178530,0.239216,0.390651,0.319620,...,1.888184,0.115265,4.255919,0.029037,NaN,3.446213,-1.007350,0.806074,1.858609,398.622235
3,0.497446,-0.049535,0.141023,0.141023,1.194801,0.000026,-1.032371,0.818995,NaN,0.031635,...,0.100983,0.907092,4.645116,-0.255313,1.797700,1.005194,1.278741,-0.818691,2.812549,527.945234
4,0.605701,1.453710,0.126049,0.126049,-0.635441,0.600073,0.776764,0.907868,-0.180334,0.662187,...,-0.894951,NaN,-1.337387,0.393958,-0.373289,0.427955,-0.726291,1.274686,10.512384,575.052682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,NaN,-0.837980,0.857335,0.857335,-0.900921,0.305825,-1.759959,0.379284,-0.431987,-0.534191,...,0.481267,NaN,6.246344,1.023857,-0.428366,NaN,0.667137,-0.308231,2.791238,235.995368
11996,0.881287,1.647118,NaN,0.239317,-1.544021,0.205085,-0.387830,0.252647,0.550154,0.167350,...,1.700230,-1.311655,-8.038122,0.146051,1.340027,-0.228400,-0.535165,-0.142828,-7.382469,421.925749
11997,0.061169,-0.483820,0.879857,NaN,-0.161385,0.914789,-1.050923,0.051287,0.019750,0.173550,...,1.761554,-1.122804,3.745146,-0.132992,-0.812099,-1.522920,-0.115161,0.182573,2.058194,206.700030
11998,0.715243,-1.030500,0.014586,0.014586,0.165240,0.285510,1.637212,0.933848,0.169283,0.708749,...,0.929562,-0.172041,3.586954,0.457671,-1.395188,1.438169,-0.339109,0.069263,3.009714,605.979254
11999,0.284834,0.506821,0.088109,0.088109,-2.330336,0.619314,NaN,0.585977,-0.645238,0.198801,...,-0.906718,-1.108863,-1.158125,0.644874,1.842947,-1.276094,0.489357,0.290644,9.900477,674.972934

In [200]:
df.drop_duplicates(inplace=True)
df_test.drop_duplicates(inplace=True)
X_test = df_test.copy()

In [201]:
X = df.drop('CORRUCYSTIC_DENSITY', axis=1)
y = df['CORRUCYSTIC_DENSITY']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

num = list(X_train.select_dtypes(exclude='object').columns)
obj = list(X_train.select_dtypes(include='object').columns)

In [202]:
for i in obj:
    print(df[i].isnull().sum())

882
883
1793

In [203]:
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('power', PowerTransformer(method='yeo-johnson')),
    ('std_scaler', StandardScaler())
])

cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),
    ('one_hot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer([
    ('num', num_pipe, num),
    ('cat', cat_pipe, obj)
])

In [204]:
def objective(trial):
    model_name = trial.suggest_categorical('model', ['xgboost', 'lightgbm', 'random_forest', 'elastic_net'])
    
    if model_name == 'xgboost':
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
            'max_depth': trial.suggest_int('max_depth', 3, 8),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            'subsample': trial.suggest_float('subsample', 0.6, 0.9),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
            'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True)
        }
        model = XGBRegressor(**params, random_state=42, n_jobs=-1)
    
    elif model_name == 'lightgbm':
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 2000),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            'num_leaves': trial.suggest_int('num_leaves', 20, 200),
            'max_depth': trial.suggest_int('max_depth', 3, 10),
            'feature_fraction': trial.suggest_float('feature_fraction', 0.6, 1.0),
            'bagging_fraction': trial.suggest_float('bagging_fraction', 0.6, 1.0),
            'bagging_freq': trial.suggest_int('bagging_freq', 1, 7),
            'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True)
        }
        model = LGBMRegressor(**params, random_state=42, n_jobs=-1, verbose=-1)
    
    elif model_name == 'random_forest':
        params = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
            'max_depth': trial.suggest_int('max_depth', 5, 25),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20),
            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2'])
        }
        model = RandomForestRegressor(**params, random_state=42, n_jobs=-1)
        
    elif model_name == 'elastic_net':
        params = {
            'alpha': trial.suggest_float('alpha', 1e-4, 1.0, log=True),
            'l1_ratio': trial.suggest_float('l1_ratio', 0.1, 1.0)
        }
        model = ElasticNet(**params, random_state=42)

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])
    
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_val)
    
    rmse = np.sqrt(np.mean((y_val - y_pred) ** 2))
    return rmse

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=1000)

[I 2025-08-26 13:32:54,806] A new study created in memory with name: no-name-0b31ed22-f782-46ba-9d13-e07baf0c2776
[I 2025-08-26 13:32:55,309] Trial 0 finished with value: 187.1002467516991 and parameters: {'model': 'elastic_net', 'alpha': 0.009163906812582877, 'l1_ratio': 0.6053586195719215}. Best is trial 0 with value: 187.1002467516991.
[I 2025-08-26 13:32:58,000] Trial 1 finished with value: 183.3461984607448 and parameters: {'model': 'random_forest', 'n_estimators': 609, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 13, 'max_features': 'sqrt'}. Best is trial 1 with value: 183.3461984607448.
[I 2025-08-26 13:32:58,470] Trial 2 finished with value: 187.0815986423316 and parameters: {'model': 'elastic_net', 'alpha': 0.008970914620468616, 'l1_ratio': 0.47573264280248484}. Best is trial 1 with value: 183.3461984607448.
[I 2025-08-26 13:32:59,696] Trial 3 finished with value: 175.59433286935783 and parameters: {'model': 'lightgbm', 'n_estimators': 533, 'learning_rate': 0.11749169197790481, 'num_leaves': 28, 'max_depth': 10, 'feature_fraction': 0.6384365036979842, 'bagging_fraction': 0.8883289755041015, 'bagging_freq': 3, 'min_child_samples': 38, 'reg_alpha': 8.210579753971995e-07, 'reg_lambda': 2.8555479279601963}. Best is trial 3 with value: 175.59433286935783.
[I 2025-08-26 13:33:02,119] Trial 4 finished with value: 174.7261769349687 and parameters: {'model': 'xgboost', 'n_estimators': 441, 'max_depth': 7, 'learning_rate': 0.02808494328084583, 'subsample': 0.8941909662995049, 'colsample_bytree': 0.6089548700767826, 'gamma': 0.011987797694367378, 'reg_alpha': 4.249281757196044e-06, 'reg_lambda': 0.0005869264649435104}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:04,356] Trial 5 finished with value: 179.35006135122737 and parameters: {'model': 'lightgbm', 'n_estimators': 1735, 'learning_rate': 0.031953015142732286, 'num_leaves': 148, 'max_depth': 5, 'feature_fraction': 0.7597415986503675, 'bagging_fraction': 0.9632649045945137, 'bagging_freq': 3, 'min_child_samples': 53, 'reg_alpha': 0.020321709115501303, 'reg_lambda': 4.594926906412547e-05}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:04,921] Trial 6 finished with value: 185.85977495330314 and parameters: {'model': 'lightgbm', 'n_estimators': 131, 'learning_rate': 0.11268579467815694, 'num_leaves': 131, 'max_depth': 3, 'feature_fraction': 0.7308298241249518, 'bagging_fraction': 0.9793909905498365, 'bagging_freq': 2, 'min_child_samples': 58, 'reg_alpha': 6.290391553540414, 'reg_lambda': 0.02068259823753004}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:06,720] Trial 7 finished with value: 181.41735168379194 and parameters: {'model': 'random_forest', 'n_estimators': 371, 'max_depth': 20, 'min_samples_split': 18, 'min_samples_leaf': 12, 'max_features': 'log2'}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:07,368] Trial 8 finished with value: 187.2772688055963 and parameters: {'model': 'elastic_net', 'alpha': 0.003588840829630042, 'l1_ratio': 0.9278724534969289}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:08,251] Trial 9 finished with value: 187.26739930355032 and parameters: {'model': 'elastic_net', 'alpha': 0.00046075233928267794, 'l1_ratio': 0.21951662050805443}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:12,745] Trial 10 finished with value: 175.79893699714904 and parameters: {'model': 'xgboost', 'n_estimators': 806, 'max_depth': 7, 'learning_rate': 0.011883491762975781, 'subsample': 0.8882409963295305, 'colsample_bytree': 0.6099033312863914, 'gamma': 0.03255370935103495, 'reg_alpha': 1.1621029728772798e-08, 'reg_lambda': 5.212323748890202e-08}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:18,495] Trial 11 finished with value: 176.42991680868946 and parameters: {'model': 'xgboost', 'n_estimators': 511, 'max_depth': 8, 'learning_rate': 0.15986166283125708, 'subsample': 0.6278624978577183, 'colsample_bytree': 0.899909418813925, 'gamma': 2.2060032440887835e-06, 'reg_alpha': 5.754530245437279e-07, 'reg_lambda': 4.004924530426331}. Best is trial 4 with value: 174.7261769349687.
[I 2025-08-26 13:33:24,540] Trial 12 finished with value: 169.2480132343816 and parameters: {'model': 'xgboost', 'n_estimators': 664, 'max_depth': 8, 'learning_rate': 0.04568552763000229, 'subsample': 0.8820387636946831, 'colsample_bytree': 0.6077770501795315, 'gamma': 0.09047002411544669, 'reg_alpha': 5.47060706382877e-06, 'reg_lambda': 6.2486670021511985}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:29,414] Trial 13 finished with value: 171.2065921843385 and parameters: {'model': 'xgboost', 'n_estimators': 786, 'max_depth': 7, 'learning_rate': 0.03372316426358281, 'subsample': 0.8967354562380896, 'colsample_bytree': 0.6112418984431166, 'gamma': 0.0366564962292755, 'reg_alpha': 8.292946732248962e-05, 'reg_lambda': 0.00023700184293241314}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:34,637] Trial 14 finished with value: 170.23395063735242 and parameters: {'model': 'xgboost', 'n_estimators': 872, 'max_depth': 7, 'learning_rate': 0.04760596103352118, 'subsample': 0.8208973530214044, 'colsample_bytree': 0.7011395132411755, 'gamma': 0.7736655038467747, 'reg_alpha': 0.000511996126463444, 'reg_lambda': 6.39517913247558e-05}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:43,178] Trial 15 finished with value: 169.95590442768005 and parameters: {'model': 'xgboost', 'n_estimators': 949, 'max_depth': 8, 'learning_rate': 0.06384219443327555, 'subsample': 0.7681552255465951, 'colsample_bytree': 0.7324781266551246, 'gamma': 0.7379322529031361, 'reg_alpha': 0.0034939562723158464, 'reg_lambda': 6.335758108045803e-07}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:51,456] Trial 16 finished with value: 170.66956389498347 and parameters: {'model': 'xgboost', 'n_estimators': 923, 'max_depth': 8, 'learning_rate': 0.06722828754388233, 'subsample': 0.7318387177083635, 'colsample_bytree': 0.7629829262674307, 'gamma': 0.0001779864957169724, 'reg_alpha': 0.01897746821685994, 'reg_lambda': 6.912236192206105e-08}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:54,161] Trial 17 finished with value: 175.05007258135976 and parameters: {'model': 'xgboost', 'n_estimators': 994, 'max_depth': 5, 'learning_rate': 0.06519760707350253, 'subsample': 0.7543187413291321, 'colsample_bytree': 0.7380222156627063, 'gamma': 0.49706170582810083, 'reg_alpha': 0.002376744960318171, 'reg_lambda': 2.8162446647805824e-06}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:33:59,994] Trial 18 finished with value: 172.76339832125123 and parameters: {'model': 'xgboost', 'n_estimators': 673, 'max_depth': 8, 'learning_rate': 0.014896893485289142, 'subsample': 0.7871327469348136, 'colsample_bytree': 0.8246721551169873, 'gamma': 0.0005168676482358292, 'reg_alpha': 1.0099791310337776, 'reg_lambda': 0.03753501081653494}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:34:03,357] Trial 19 finished with value: 173.34156301244573 and parameters: {'model': 'xgboost', 'n_estimators': 965, 'max_depth': 6, 'learning_rate': 0.06635221054865352, 'subsample': 0.6693064137148117, 'colsample_bytree': 0.6770584346798466, 'gamma': 2.3724916341741725e-08, 'reg_alpha': 3.836763000292015e-05, 'reg_lambda': 1.5638779869514998e-06}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:34:07,122] Trial 20 finished with value: 177.9313147417364 and parameters: {'model': 'random_forest', 'n_estimators': 708, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 12 with value: 169.2480132343816.
[I 2025-08-26 13:34:14,602] Trial 21 finished with value: 168.44097634454198 and parameters: {'model': 'xgboost', 'n_estimators': 896, 'max_depth': 8, 'learning_rate': 0.04762182190836712, 'subsample': 0.8209553736848888, 'colsample_bytree': 0.7073010921428894, 'gamma': 0.7028087101258599, 'reg_alpha': 0.001035981695808318, 'reg_lambda': 5.824064967476802e-06}. Best is trial 21 with value: 168.44097634454198.
[I 2025-08-26 13:34:22,833] Trial 22 finished with value: 168.3172205476283 and parameters: {'model': 'xgboost', 'n_estimators': 989, 'max_depth': 8, 'learning_rate': 0.04705992539703429, 'subsample': 0.827770714448999, 'colsample_bytree': 0.6773120279622981, 'gamma': 0.8371159280742799, 'reg_alpha': 0.010074122405419246, 'reg_lambda': 4.9146101897765945e-06}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:24,242] Trial 23 finished with value: 183.79542649946748 and parameters: {'model': 'xgboost', 'n_estimators': 998, 'max_depth': 3, 'learning_rate': 0.019721332875419464, 'subsample': 0.8398882945056435, 'colsample_bytree': 0.6661862198943599, 'gamma': 0.0066706216990563925, 'reg_alpha': 0.18729853448472744, 'reg_lambda': 7.377135475040911e-06}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:27,118] Trial 24 finished with value: 173.04982908884108 and parameters: {'model': 'xgboost', 'n_estimators': 828, 'max_depth': 6, 'learning_rate': 0.04634360153294914, 'subsample': 0.8384868947839844, 'colsample_bytree': 0.6525579311507994, 'gamma': 0.15168270238308534, 'reg_alpha': 1.786092412326738e-05, 'reg_lambda': 0.0020096908770585306}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:33,875] Trial 25 finished with value: 170.1585574321781 and parameters: {'model': 'xgboost', 'n_estimators': 685, 'max_depth': 8, 'learning_rate': 0.024075878375750266, 'subsample': 0.8139400337257505, 'colsample_bytree': 0.7859055182436326, 'gamma': 0.003287615400607921, 'reg_alpha': 0.0006466427710349989, 'reg_lambda': 1.3795439642219703e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:35,616] Trial 26 finished with value: 180.97009405530605 and parameters: {'model': 'xgboost', 'n_estimators': 880, 'max_depth': 4, 'learning_rate': 0.04124850034422234, 'subsample': 0.8605548989720289, 'colsample_bytree': 0.7020592618989103, 'gamma': 0.11740689014395529, 'reg_alpha': 0.03930505570808529, 'reg_lambda': 2.574963325208976e-07}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:38,209] Trial 27 finished with value: 178.45045406169493 and parameters: {'model': 'lightgbm', 'n_estimators': 1270, 'learning_rate': 0.09530657016192877, 'num_leaves': 199, 'max_depth': 9, 'feature_fraction': 0.9355431242508038, 'bagging_fraction': 0.6007341137393167, 'bagging_freq': 7, 'min_child_samples': 99, 'reg_alpha': 5.909080893251295e-08, 'reg_lambda': 0.28411106332700453}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:39,448] Trial 28 finished with value: 183.85779373616123 and parameters: {'model': 'random_forest', 'n_estimators': 225, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 19, 'max_features': 'log2'}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:39,931] Trial 29 finished with value: 186.1924979858995 and parameters: {'model': 'elastic_net', 'alpha': 0.8988061765452644, 'l1_ratio': 0.10287373780848347}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:42,505] Trial 30 finished with value: 172.0267038150437 and parameters: {'model': 'xgboost', 'n_estimators': 747, 'max_depth': 6, 'learning_rate': 0.04650936663911546, 'subsample': 0.7977556656056453, 'colsample_bytree': 0.6379810447722716, 'gamma': 8.65142407635624e-06, 'reg_alpha': 0.0001835567727045156, 'reg_lambda': 1.423841246353791e-08}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:51,114] Trial 31 finished with value: 169.0626328500957 and parameters: {'model': 'xgboost', 'n_estimators': 920, 'max_depth': 8, 'learning_rate': 0.06083532707118964, 'subsample': 0.7594247808345599, 'colsample_bytree': 0.7373153830100392, 'gamma': 0.7886871210643617, 'reg_alpha': 0.003907221426794802, 'reg_lambda': 7.186566145146386e-07}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:34:55,965] Trial 32 finished with value: 170.10915776470796 and parameters: {'model': 'xgboost', 'n_estimators': 890, 'max_depth': 7, 'learning_rate': 0.08883028709037571, 'subsample': 0.7160403850839354, 'colsample_bytree': 0.7068481298612848, 'gamma': 0.11915212906488318, 'reg_alpha': 0.0032609720739253654, 'reg_lambda': 7.1471406612113e-07}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:04,244] Trial 33 finished with value: 169.1648399569924 and parameters: {'model': 'xgboost', 'n_estimators': 994, 'max_depth': 8, 'learning_rate': 0.055796239463030015, 'subsample': 0.8573205276630038, 'colsample_bytree': 0.6869348529227288, 'gamma': 0.7718423881421215, 'reg_alpha': 0.0989681955856241, 'reg_lambda': 1.819229417901542e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:12,588] Trial 34 finished with value: 169.19398447310002 and parameters: {'model': 'xgboost', 'n_estimators': 1000, 'max_depth': 8, 'learning_rate': 0.05591140685752679, 'subsample': 0.8541223718136581, 'colsample_bytree': 0.6875655434712874, 'gamma': 0.9080119364455874, 'reg_alpha': 0.1584702635648491, 'reg_lambda': 1.9354412627802225e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:16,005] Trial 35 finished with value: 181.67317203607448 and parameters: {'model': 'random_forest', 'n_estimators': 927, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'log2'}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:20,736] Trial 36 finished with value: 172.42785179801464 and parameters: {'model': 'xgboost', 'n_estimators': 843, 'max_depth': 7, 'learning_rate': 0.08109496189725318, 'subsample': 0.7968757959668767, 'colsample_bytree': 0.7267505755399174, 'gamma': 0.8947037861770576, 'reg_alpha': 0.0958330736632677, 'reg_lambda': 4.546048439842418e-06}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:23,277] Trial 37 finished with value: 177.74365459326881 and parameters: {'model': 'lightgbm', 'n_estimators': 1214, 'learning_rate': 0.036435768181350775, 'num_leaves': 23, 'max_depth': 9, 'feature_fraction': 0.9926784253484565, 'bagging_fraction': 0.6770791711008741, 'bagging_freq': 7, 'min_child_samples': 8, 'reg_alpha': 0.005748948091886339, 'reg_lambda': 0.00011611369200850408}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:23,774] Trial 38 finished with value: 186.2309008678463 and parameters: {'model': 'elastic_net', 'alpha': 0.8053129788676456, 'l1_ratio': 0.8782600919863088}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:28,194] Trial 39 finished with value: 171.39232224828507 and parameters: {'model': 'xgboost', 'n_estimators': 767, 'max_depth': 7, 'learning_rate': 0.05568049392667138, 'subsample': 0.8190762596206805, 'colsample_bytree': 0.7693192605301121, 'gamma': 0.15619695018914884, 'reg_alpha': 0.6508823296783242, 'reg_lambda': 1.751342764398704e-07}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:30,544] Trial 40 finished with value: 178.53700088210053 and parameters: {'model': 'lightgbm', 'n_estimators': 1202, 'learning_rate': 0.023804572916853072, 'num_leaves': 81, 'max_depth': 9, 'feature_fraction': 0.8712844432427032, 'bagging_fraction': 0.7575536683139957, 'bagging_freq': 5, 'min_child_samples': 100, 'reg_alpha': 0.0009645037776544363, 'reg_lambda': 0.0013240439027387982}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:38,277] Trial 41 finished with value: 170.32665396654969 and parameters: {'model': 'xgboost', 'n_estimators': 935, 'max_depth': 8, 'learning_rate': 0.05555724464766767, 'subsample': 0.8549823888916068, 'colsample_bytree': 0.6842927061461489, 'gamma': 0.9170959898649328, 'reg_alpha': 0.34400052586546, 'reg_lambda': 1.9381417169417625e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:47,767] Trial 42 finished with value: 170.10027616096818 and parameters: {'model': 'xgboost', 'n_estimators': 972, 'max_depth': 8, 'learning_rate': 0.0753282133745876, 'subsample': 0.858065766222445, 'colsample_bytree': 0.6955694848743544, 'gamma': 0.24983079931229257, 'reg_alpha': 0.04576738535431341, 'reg_lambda': 1.9093913314548198e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:35:56,995] Trial 43 finished with value: 169.4309452018098 and parameters: {'model': 'xgboost', 'n_estimators': 902, 'max_depth': 8, 'learning_rate': 0.053777323644951976, 'subsample': 0.8379144856375916, 'colsample_bytree': 0.6492686191271206, 'gamma': 0.04302811730113164, 'reg_alpha': 3.220471253230257, 'reg_lambda': 2.4781735194850276e-06}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:02,346] Trial 44 finished with value: 170.94063809117944 and parameters: {'model': 'xgboost', 'n_estimators': 859, 'max_depth': 7, 'learning_rate': 0.03911285655058758, 'subsample': 0.7043727802555935, 'colsample_bytree': 0.7125954958137557, 'gamma': 0.23940202153420584, 'reg_alpha': 0.011724859666245892, 'reg_lambda': 7.917653758657569e-07}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:03,325] Trial 45 finished with value: 187.40529923159838 and parameters: {'model': 'elastic_net', 'alpha': 0.00013463130162778077, 'l1_ratio': 0.5935177184083447}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:10,636] Trial 46 finished with value: 171.15552239225636 and parameters: {'model': 'xgboost', 'n_estimators': 973, 'max_depth': 8, 'learning_rate': 0.10605652954341017, 'subsample': 0.7733602820982377, 'colsample_bytree': 0.6633950657246069, 'gamma': 0.9997942031944111, 'reg_alpha': 0.07311256692848608, 'reg_lambda': 4.965960452108686e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:13,250] Trial 47 finished with value: 183.99200195511895 and parameters: {'model': 'random_forest', 'n_estimators': 607, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 'sqrt'}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:15,593] Trial 48 finished with value: 175.90972911186444 and parameters: {'model': 'xgboost', 'n_estimators': 355, 'max_depth': 7, 'learning_rate': 0.028968638228927455, 'subsample': 0.8607387948209184, 'colsample_bytree': 0.7492806172621673, 'gamma': 0.001988915182096186, 'reg_alpha': 0.009954862979736502, 'reg_lambda': 0.00031768501419778537}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:20,619] Trial 49 finished with value: 169.85746128505218 and parameters: {'model': 'xgboost', 'n_estimators': 817, 'max_depth': 7, 'learning_rate': 0.056517683110474906, 'subsample': 0.8130579986374697, 'colsample_bytree': 0.7211642737024252, 'gamma': 0.01755570330056201, 'reg_alpha': 0.18764403539472774, 'reg_lambda': 8.003402650771032e-06}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:25,419] Trial 50 finished with value: 175.93524017380705 and parameters: {'model': 'xgboost', 'n_estimators': 922, 'max_depth': 7, 'learning_rate': 0.1398763526011816, 'subsample': 0.8654248745799508, 'colsample_bytree': 0.6330221629221098, 'gamma': 0.243864706053539, 'reg_alpha': 1.372734863365307, 'reg_lambda': 2.718497553543738e-05}. Best is trial 22 with value: 168.3172205476283.
[I 2025-08-26 13:36:29,647] Trial 51 finished with value: 170.05320105588672 and parameters: {'model': 'xgboost', 'n_estimators': 498, 'max_depth': 8, 'learning_rate': 0.042184065705452946, 'subsample': 0.8830807667845458, 'colsample_bytree': 0.6824252687634105, 'gamma': 0.06751103592450833, 'reg_alpha': 8.486712714077685e-06, 'reg_lambda': 0.712116050788488}. Best is trial 22 with value: 168.3172205476283.

KeyboardInterrupt:

In [205]:
best_model_name = study.best_trial.params['model']
print(f"Best model: {best_model_name}")
best_params = {k: v for k, v in study.best_trial.params.items() if k != 'model'}
if best_model_name == 'xgboost':
    best_model = XGBRegressor(**best_params, random_state=42)
elif best_model_name == 'lightgbm':
    best_model = LGBMRegressor(**best_params, random_state=42)
elif best_model_name == 'random_forest':
    best_model = RandomForestRegressor(**best_params, random_state=42)
else:
    best_model = ElasticNet(**best_params, random_state=42)
model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', best_model)
])
model.fit(X_train, y_train)
model.score(X_val, y_val)

Best model: lightgbm

  File "c:\Users\dsapu\Project\conda\condasystem\envs\dmsdl\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\dsapu\Project\conda\condasystem\envs\dmsdl\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dsapu\Project\conda\condasystem\envs\dmsdl\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\dsapu\Project\conda\condasystem\envs\dmsdl\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[LightGBM] [Warning] feature_fraction is set=0.8032560369868035, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8032560369868035
[LightGBM] [Warning] bagging_fraction is set=0.8569100979234635, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8569100979234635
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Warning] feature_fraction is set=0.8032560369868035, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8032560369868035
[LightGBM] [Warning] bagging_fraction is set=0.8569100979234635, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8569100979234635
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002197 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 11017
[LightGBM] [Info] Number of data points in the train set: 8820, number of used features: 69
[LightGBM] [Info] Start training from score 448.976320
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

0.1988233564902443

In [206]:
predictions = model.predict(X_test)
submission = pd.DataFrame({
    'LOCAL_IDENTIFIER': X_test.index,
    'CORRUCYSTIC_DENSITY': predictions
})
submission.to_csv('submission.csv', index=False)

[LightGBM] [Warning] feature_fraction is set=0.8032560369868035, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8032560369868035
[LightGBM] [Warning] bagging_fraction is set=0.8569100979234635, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8569100979234635
[LightGBM] [Warning] bagging_freq is set=1, subsample_freq=0 will be ignored. Current value: bagging_freq=1

# dataset and dataloader

In [ ]:
# import torch.nn as nn
# import torch
# import torch.nn.functional as F
# import torch.optim as optim
# from torch.utils.data import DataLoader, TensorDataset
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from tqdm import tqdm

# import pytorch_lightning as pl
# import pytorch_optimizer as optim1
# from torchmetrics.regression import MeanSquaredError, R2Score
# from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping, LearningRateMonitor
# import torchmetrics
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
# device

In [ ]:
# X_train = torch.tensor(X_train, dtype=torch.float32)
# y_train = torch.tensor(y_train.values, dtype=torch.float32)

# X_val = torch.tensor(X_val, dtype=torch.float32)
# y_val = torch.tensor(y_val.values, dtype=torch.float32)

In [ ]:
# train_data = TensorDataset(X_train, y_train)
# train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
# val_data = TensorDataset(X_val, y_val)
# val_loader = DataLoader(val_data, batch_size=64, shuffle=False)

In [ ]:
# def conv_block(in_feature, out_feature, padding=1, stride=1,
#              activation="relu", pool =True, maxpool=True, kernel_size=3,
#              kernel_size_pool=2, pool_stride=2)-> list[nn.Sequential]:
#     layers = [nn.Conv2d(in_feature, out_feature, kernel_size=kernel_size, padding=padding, stride=stride)]
#     if activation == "relu":
#         layers.append(nn.ReLU())
#     elif activation == "leakyrelu":
#         layers.append(nn.LeakyReLU())
#     elif activation == "sigmoid":
#         layers.append(nn.Sigmoid())
#     elif activation == "tanh":
#         layers.append(nn.Tanh())
#     if pool:
#         if maxpool:
#             layers.append(nn.MaxPool2d(kernel_size=kernel_size_pool, stride=pool_stride))
#         else:
#             layers.append(nn.AvgPool2d(kernel_size=kernel_size_pool, stride=pool_stride))
#     else:
#         layers.append(nn.Identity())
#     return nn.Sequential(*layers)


# import torch.nn as nn

# def linear_block(in_features, out_features, batch_norm=False, activation=None, dropout=0.0):
#     """
#     Membuat blok sekuensial yang terdiri dari Linear, BatchNorm (opsional), 
#     Aktivasi (opsional), dan Dropout (opsional).
#     """
#     layers = [nn.Linear(in_features, out_features)]
#     if batch_norm:
#         layers.append(nn.BatchNorm1d(out_features))
#     if activation == 'relu':
#         layers.append(nn.ReLU())
#     elif activation == 'sigmoid':
#         layers.append(nn.Sigmoid())
#     elif activation == 'tanh':
#         layers.append(nn.Tanh())
#     elif activation == 'leakyrelu':
#         layers.append(nn.LeakyReLU(0.1)) 
#     elif activation == 'softmax':
#         layers.append(nn.Softmax(dim=1))
#     elif activation == 'elu':
#         layers.append(nn.ELU())
#     elif activation == 'selu':
#         layers.append(nn.SELU())
#     elif activation == 'lsoftmax':
#         layers.append(nn.LogSoftmax(dim=1))
        
#     if dropout > 0.0:
#         layers.append(nn.Dropout(dropout))
        
#     return nn.Sequential(*layers)

In [ ]:
# class ANN(pl.LightningModule):
#     def __init__(self, input_size, learning_rate, pos_weight_tensor, dropout=0):
#         super(ANN, self).__init__()
#         self.learning_rate = learning_rate
#         self.save_hyperparameters()
#         self.criterion = nn.MSELoss()
#         self.mae = MeanSquaredError()
#         self.r2_score = R2Score()
#         self.fc = nn.Sequential(
#             linear_block(input_size, 128, activation='leakyrelu', batch_norm=True),
#             linear_block(128, 64, activation='leakyrelu', batch_norm=True),
#             linear_block(64, 32, activation='leakyrelu', batch_norm=True),
#             linear_block(32, 1, activation=None)
#         )
#     def forward(self, x):
#         return self.fc(x)

#     def training_step(self, batch, batch_idx):
#         inputs, labels = batch
#         labels = labels.unsqueeze(1) 
#         outputs = self(inputs)
#         loss = self.criterion(outputs, labels)
#         mae = self.mae(outputs, labels)
#         r2 = self.r2_score(outputs, labels)
#         self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True, logger=True)
#         self.log('train_mae', mae, on_step=False, on_epoch=True, prog_bar=True, logger=True)
#         self.log('train_r2', r2, on_step=False, on_epoch=True, prog_bar=True, logger=True)
        
#         return loss

#     def validation_step(self, batch, batch_idx):
#         inputs, labels = batch
#         labels = labels.unsqueeze(1)
#         outputs = self(inputs)
#         loss = self.criterion(outputs, labels)
#         mae = self.mae(outputs, labels)
#         r2 = self.r2_score(outputs, labels)
#         self.log('val_loss', loss, on_epoch=True, prog_bar=True, logger=True)
#         self.log('val_mae', mae, on_epoch=True, prog_bar=True, logger=True)
#         self.log('val_r2', r2, on_epoch=True, prog_bar=True, logger=True)

#     def test_step(self, batch, batch_idx):
#         inputs, labels = batch
#         labels = labels.unsqueeze(1)
#         outputs = self(inputs)
#         loss = self.criterion(outputs, labels)
#         mae = self.mae(outputs, labels)
#         r2 = self.r2_score(outputs, labels)
#         self.log('test_loss', loss, on_epoch=True, prog_bar=True, logger=True)
#         self.log('test_mae', mae, on_epoch=True, prog_bar=True, logger=True)
#         self.log('test_r2', r2, on_epoch=True, prog_bar=True, logger=True)

#     def backward(self, loss, *args, **kwargs):
#         loss.backward(create_graph=True)

#     def configure_optimizers(self):
#         optimizer = optim1.AdamW(self.parameters(), lr=self.learning_rate, weight_decay=1e-4)
#         return optimizer

#     def predict_step(self, batch, batch_idx, dataloader_idx=None):
#         if isinstance(batch, list) or isinstance(batch, tuple):
#             inputs, _ = batch
#         else:
#             inputs = batch
#         return self(inputs)

In [ ]:
# X_train.shape[1]

# Config

In [ ]:
# if torch.cuda.is_available():
#     accelerator_type = 'gpu'
#     devices_to_use = 1
# else:
#     accelerator_type = 'cpu'
#     devices_to_use = 'auto'

# checkpoint_callback = ModelCheckpoint(
#     monitor='val_r2',
#     dirpath='checkpoints/',
#     filename='GDSC-{epoch:02d}-{val_loss:.4f}',
#     save_top_k=1,
#     mode='max'
# )
# early_stopping = EarlyStopping(
#     monitor='val_r2',
#     patience=10,
#     mode='max',
# )
# lr_monitor_callback = LearningRateMonitor(logging_interval='epoch')

# trainer1 = pl.Trainer(
#     max_epochs=3000,
#     callbacks=[checkpoint_callback, early_stopping, lr_monitor_callback],
#     logger=pl.loggers.TensorBoardLogger("tb_logs", name="simple_model_experiment"),
#     accelerator=accelerator_type,
#     devices=devices_to_use,
#     log_every_n_steps=10,
#     gradient_clip_val=0.5,
#     deterministic=True
# )

# model = ANN(input_size=X_train.shape[1], learning_rate=0.0005, pos_weight_tensor=None, dropout=0)

In [ ]:
# from pytorch_lightning.tuner import Tuner
# print("--- Menjalankan Learning Rate Finder ---")
# # Buat objek Tuner dari trainer Anda
# tuner = Tuner(trainer1)

# # Jalankan lr_find
# lr_finder = tuner.lr_find(model, train_loader, val_loader)

# # Ambil learning rate yang disarankan
# suggested_lr = lr_finder.suggestion()
# print(f"Saran learning rate dari tuner: {suggested_lr}")

# # Perbarui learning rate di model Anda
# model.learning_rate = suggested_lr
# # atau jika Anda menggunakan hparams: model.hparams.learning_rate = suggested_lr

# # Tampilkan plot untuk dianalisis (opsional)
# fig = lr_finder.plot(suggest=True)
# fig.show()

In [ ]:
# trainer1.fit(model, train_loader, val_loader)

In [ ]:
# trainer1.validate(model, val_loader, ckpt_path='best')